# Shell variables
# Generated by 'wal'
wallpaper='/home/dropdead/Pictures/walbangerhanger/yakyakyak.png'

# Special
background='#010101'
foreground='#dcdcdd'
cursor='#dcdcdd'

# Colors
color0='#010101'
color1='#C66957'
color2='#A78179'
color3='#D98170'
color4='#F08772'
color5='#5F7F9D'
color6='#BDA8A3'
color7='#dcdcdd'
color8='#9a9a9a'
color9='#C66957'
color10='#A78179'
color11='#D98170'
color12='#F08772'
color13='#5F7F9D'
color14='#BDA8A3'
color15='#dcdcdd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
